apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sslproxies.ssl-proxy.vliubezny
spec:
  group: ssl-proxy.vliubezny
  names:
    kind: SslProxy
    listKind: SslProxyList
    plural: sslproxies
    singular: sslproxy
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: SslProxy is the Schema for the sslproxies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SslProxySpec defines the desired state of SslProxy
            properties:
              networkEndpointGroup:
                description: Name of network endpoint group used as SSL Proxy backend
                minLength: 1
                type: string
              serviceName:
                description: Name of service to proxy TCP connection to
                minLength: 1
                type: string
              servicePort:
                description: Port of service to proxy TCP connection to
                minLength: 1
                type: string
              zone:
                description: GCP zone of KGE cluster
                minLength: 1
                type: string
            required:
            - networkEndpointGroup
            - serviceName
            - servicePort
            - zone
            type: object
          status:
            description: SslProxyStatus defines the observed state of SslProxy
            properties:
              endpoints:
                description: List of configured endpoints
                items:
                  type: string
                type: array
            required:
            - endpoints
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
